name:                  Check, Test and Build cross-compilation Suite

on:
  pull_request:
  push:
    branches:
      - master
      - stable
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
  check:
    name:              Check cross
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:        #List of [supported targets](https://github.com/rust-embedded/cross#supported-targets)
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- armv7-unknown-linux-gnueabihf
          #- armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    runs-on:           ubuntu-latest
    container:         generalbeck/docker-cross-rust:${{matrix.target}}
    env:
      RUST_BACKTRACE:  full
    steps:
      - name:          Checkout sources & submodules
        uses:          actions/checkout@master
        with:
          fetch-depth: 5
          submodules:  recursive
      - name:          Install toolchain
        id:            toolchain
        uses:          actions-rs/toolchain@master
        with:
          profile:     minimal
          toolchain:   ${{ matrix.toolchain }}
          target:      ${{ matrix.target }}
          components:  clippy, rustfmt
          override:    true
      - name:          Set cache_hash ENV and prepare cache dir's
        run:           |
          echo ::set-env name=cache_hash::${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.toml') }}
          mkdir -p $HOME/sccache
        shell:         bash
      - name:          Cache cargo registry
        uses:          actions/cache@master
        with:
          path:        $HOME/.cargo/registry
          key:         cargo-registry-${{ env['cache_hash'] }}
      - name:          Cache cargo index
        uses:          actions/cache@master
        with:
          path:        $HOME/.cargo/git
          key:         cargo-git-${{ env['cache_hash'] }}
      - name:          Cache cargo build
        uses:          actions/cache@master
        with:
          path:        target
          key:         cargo-target-${{ env['cache_hash'] }}
      - name:          Cache sccache
        uses:          actions/cache@master
        with:
          path:        "$HOME/sccache"
          key:         sccache-${{ env['cache_hash'] }}
      - name:          Sccache statistics
        run:           sccache --show-stats
      - name:          Checking ${{ matrix.target }}-${{ matrix.toolchain }}
        uses:          actions-rs/cargo@master
        with:
          command:     check
          args:        --target ${{ matrix.target }} --all --verbose
      - name:          Stop sccache
        if:            always()
        run:           sccache --stop-server
  test:
    name:              Test cross
    needs:             [check]
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:        #List of [supported targets](https://github.com/rust-embedded/cross#supported-targets)
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- armv7-unknown-linux-gnueabihf
          #- armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    runs-on:           ubuntu-latest
    container:         generalbeck/docker-cross-rust:${{matrix.target}}
    env:
      RUST_BACKTRACE:  full
    steps:
      - name:          Checkout sources & submodules
        uses:          actions/checkout@master
        with:
          fetch-depth: 5
          submodules:  recursive
      - name:          Install toolchain
        id:            toolchain
        uses:          actions-rs/toolchain@master
        with:
          profile:     minimal
          toolchain:   ${{ matrix.toolchain }}
          target:      ${{ matrix.target }}
          components:  clippy, rustfmt
          override:    true
      - name:          Set cache_hash ENV and prepare cache dir's
        run:           |
          echo ::set-env name=cache_hash::${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.toml') }}
          mkdir -p $HOME/sccache
        shell:         bash
      - name:          Cache cargo registry
        uses:          actions/cache@master
        with:
          path:        $HOME/.cargo/registry
          key:         cargo-registry-${{ env['cache_hash'] }}
      - name:          Cache cargo index
        uses:          actions/cache@master
        with:
          path:        $HOME/.cargo/git
          key:         cargo-git-${{ env['cache_hash'] }}
      - name:          Cache cargo build
        uses:          actions/cache@master
        with:
          path:        target
          key:         cargo-target-${{ env['cache_hash'] }}
      - name:          Cache sccache
        uses:          actions/cache@master
        with:
          path:        "$HOME/sccache"
          key:         sccache-${{ env['cache_hash'] }}
      - name:          Sccache statistics
        run:           sccache --show-stats
      - name:          Testing ${{ matrix.target }}-${{ matrix.toolchain }}
        uses:          actions-rs/cargo@master
        with:
          command:     test
          args:        --target ${{ matrix.target }} --all --verbose
      - name:          Stop sccache
        if:            always()
        run:           sccache --stop-server
  build:
    name:              Build cross
    needs:             [check,test]
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
        target:        #List of [supported targets](https://github.com/rust-embedded/cross#supported-targets)
          #- aarch64-unknown-linux-gnu
          #- aarch64-unknown-linux-musl
          #- armv7-unknown-linux-gnueabihf
          #- armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-musl
    runs-on:           ubuntu-latest
    container:         generalbeck/docker-cross-rust:${{matrix.target}}
    env:
      RUST_BACKTRACE:  full
      RUSTFLAGS:       "-C link-arg=-s" #Strip binaries
    steps:
      - name:          Checkout sources & submodules
        uses:          actions/checkout@master
        with:
          fetch-depth: 5
          submodules:  recursive
      - name:          Install toolchain
        id:            toolchain
        uses:          actions-rs/toolchain@master
        with:
          profile:     minimal
          toolchain:   ${{ matrix.toolchain }}
          target:      ${{ matrix.target }}
          components:  clippy, rustfmt
          override:    true
      - name:          Set cache_hash ENV and prepare cache dir's
        run:           |
          echo ::set-env name=cache_hash::${{ runner.os }}-${{ steps.toolchain.outputs.rustc_hash }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.toml') }}
          mkdir -p $HOME/sccache
        shell:         bash
      - name:          Cache cargo registry
        uses:          actions/cache@master
        with:
          path:        $HOME/.cargo/registry
          key:         cargo-registry-${{ env['cache_hash'] }}
      - name:          Cache cargo index
        uses:          actions/cache@master
        with:
          path:        $HOME/.cargo/git
          key:         cargo-git-${{ env['cache_hash'] }}
      - name:          Cache cargo build
        uses:          actions/cache@master
        with:
          path:        target
          key:         cargo-target-${{ env['cache_hash'] }}
      - name:          Cache sccache
        uses:          actions/cache@master
        with:
          path:        "$HOME/sccache"
          key:         sccache-${{ env['cache_hash'] }}
      - name:          Sccache statistics
        run:           sccache --show-stats
      - name:          Building ${{ matrix.target }}-${{ matrix.toolchain }}
        uses:          actions-rs/cargo@master
        with:
          command:     build
          args:        --target ${{ matrix.target }} --all --verbose --release
      - name:          Stop sccache
        if:            always()
        run:           sccache --stop-server
      - name:          Prepare artifact's
        run:           .github/workflows/prepare_artifacts.sh ${{ matrix.target }}
        shell:         bash
      - name:          Upload artifact's
        uses:          actions/upload-artifact@v1
        with:
          name:        ${{ matrix.toolchain }}.${{ matrix.target }}.zip
          path:        artifacts/
